title: Fengxuan Zhang's Homepage
page-top-title: Fengxuan Zhang
top-section-bg-text: Embrace All Rivers Like the Sea, Follow Principles to Go Far
home-subtitle: Fengxuan Zhang&ensp;|&ensp;张风轩
copyright-text: '&copy; Fengxuan Zhang 2023-2025. All Rights Reserved.'
