title: Fengxuan Zhang's Homepage
page-top-title: Fengxuan Zhang
top-section-bg-text: 海纳百川 取则行远
home-subtitle: Fengxuan Zhang&ensp;|&ensp;张风轩
copyright-text: '&copy; Fengxuan Zhang 2023-2025. All Rights Reserved.'
